#!/usr/bin/env node
// purpose: post an image specified on the command line, for dev efficiency

const botkit = require('botkit')
const fs = require('fs')

var controller = botkit.slackbot({})
rmgbot = controller.spawn({
  token: process.env.TOKEN_RMGBOT,
  incoming_webhook: {
    url: process.env.WEBHOOK_RMGBOT,
  },
})

rmgbot.api.files.upload({
  channels: ['#general'],
  file: fs.createReadStream(process.argv[2]),
}, function(err, response) {
  console.log({res: response})
  if (err) { console.log({err: err}) }
})

/*
rmgbot.sendWebhook({
  channel: '#general',
  text: 'herro',
  attachments: [
    { 
      image_url: 'https://thumbs.dreamstime.com/t/block-swiss-type-cheese-white-42380855.jpg',
    },
  ],
}, function(err, res) {
})
*/
